# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: flinkoperator.k8s.io/v1alpha1
kind: FlinkCluster
metadata:
  name: flinkjobcluster-sample
spec:
  image:
    name: flink:1.8.1
    pullPolicy: Always
  jobManager:
    replicas: 1
    accessScope: Cluster
    ports:
      rpc: 6123
      blob: 6124
      query: 6125
      ui: 8081
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  taskManager:
    replicas: 2
    ports:
      data: 6121
      rpc: 6122
      query: 6125
    resources:
      limits:
        memory: "2048Mi"
        cpu: "1"
  job:
    jarFile: ./examples/batch/WordCount.jar
    className: org.apache.flink.examples.java.wordcount.WordCount
    args: ["--input", "./README.txt"]
    noLoggingToStdout: false
    parallelism: 2
    restartPolicy: OnFailure
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
